#!/bin/bash

set -e

set-git-config "$GIT_USER_EMAIL" "$GIT_USER_NAME" "$GIT_PUSH_DEFAULT"

add-ssh-key "$SSH_PUBLIC_KEY" "$SSH_PRIVATE_KEY" "$SSH_ID" "$SSH_HOST" "$SSH_USER" "$SSH_CONFIG_FILE"

import-gpg-key "$MAVEN_GPG_PASSPHRASE" "$MAVEN_GPG_KEY_VALUE"  

exec "$@"